'use strict';
//will need to split into individual language files with safety checks in time
//for now single file should suffice
define([], function () {
    return {
        "en": {
           "ABOUT": "About",
           "CONSOLE": "Console",
           "VIEW-INTRODUCTION": "View Introduction",
           "VIEWER": "Viewer",
           "APPLICATIONS": "Applications",
           "APPLICATIONS-CHART": "Applications Chart",
           "HELLO": "Hello",
           "GRID": "Grid",
           "DATAGRID": "Data Grid",
           "CHART": "Chart",
           "NEWS": "News",
           "CLOSE-TAB": "Close Tab",
           "CLOSE-ALL-TABS": "Close all tabs",
           "MOVE-ALL-TABS-TO": "Move all tabs to",
           "CLOSE-OTHER-TABS": "Close other tabs",
           "FLIP-LEFT-RIGHT": "Flip Left Right",
           "FLIP-TOP-BOTTOM": "Flip Top Bottom",
           "FLIP-ORIENTATION": "Flip Orientation",
           "COLLAPSE-RIGHT": "Collapse Right",
           "COLLAPSE-LEFT": "Collapse Left",
           "COLLAPSE-TOP": "Collapse Top",
           "COLLAPSE-BOTTOM": "Collapse Bottom",
           "MOVE-TO-LOCATION": "Move to Location",
           "SWITCH-USER": "Switch User",
           "PREFERENCES": "Preferences",
           "OPEN-GADGETS-MENU": "Open Gadgets Menu",
           "OPEN-APPLICATIONS": "Open Applications",
           "OPEN-APPLICATIONS-CHART": "Open Applications Chart",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "Open News",
           "OPEN-CHART": "Open Chart",
           "NEWS-DATA-1": "Sample Intranet News",
           "APPLICATIONS-DATA-1": "Demonstrates workflow data via charts",
           "OPEN-IN-NEW-WINDOW": "Open in new window",
           "OPEN-VIEWER": "Open Viewer",
           "GO-TO-CONSOLE": "Go to Console",
           "WINDOW": "Window",
           "THIS-WINDOW": "This window",
           "COMPARE": "Compare",
           "MAIN-ZONE-MESSAGE": "Click on toolbar gadget controls to open gadgets!",
           "LOADING": "Loading",
           "GADGETS-ON-PANEL": "Gadgets on this panel",
           "GADGETS-ACTIONS": "Gadget Actions",
           "OPEN-IN": "Open in",
           "CLOSE": "Close",
           "MOVE-TO": "Move to",
           "GADGET-OPENED-HERE": "Gadget currently opened here",
           "NEW-WINDOW": "New window",
           "AWESOME": "Awesome",
           "HOW-ARE-YOU": "How are you",
           "INCOMES": "Incomes",
           "INCOMESCHART": "Incomes Chart",
           "MAP": "Map",
           "DESKTOP-MODE": "Switch to desktop mode",
           "MOBILE-MODE": "Switch to mobile mode",
           "PERFORMANCE": "High Performance Grid"
        },
        "zn-ch": {
           "ABOUT": "关于",
           "CONSOLE": "安慰",
           "VIEW-INTRODUCTION": "查看简介",
           "VIEWER": "查看器",
           "APPLICATIONS": "应用",
           "APPLICATIONS-CHART": "应用图",
           "HELLO": "你好",
           "GRID": "格",
           "DATAGRID": "数据网格",
           "CHART": "图表",
           "NEWS": "新闻",
           "CLOSE-TAB": "关闭标签页",
           "CLOSE-ALL-TABS": "关闭所有标签页",
           "MOVE-ALL-TABS-TO": "将所有选项卡",
           "CLOSE-OTHER-TABS": "关闭其他标签页",
           "FLIP-LEFT-RIGHT": "翻转向左向右",
           "FLIP-TOP-BOTTOM": "翻转顶部底部",
           "FLIP-ORIENTATION": "翻转方向",
           "COLLAPSE-RIGHT": "关闭右",
           "COLLAPSE-LEFT": "倒台",
           "COLLAPSE-TOP": "关闭顶部",
           "COLLAPSE-BOTTOM": "折叠底",
           "MOVE-TO-LOCATION": "移动到另一个位置",
           "SWITCH-USER": "切换用户",
           "PREFERENCES": "优先",
           "OPEN-GADGETS-MENU": "打开小工具菜单",
           "OPEN-APPLICATIONS": "打开应用程序",
           "OPEN-APPLICATIONS-CHART": "打开应用程序图",
           "OPEN-GRID": "开放网格",
           "OPEN-NEWS": "打开新闻",
           "OPEN-CHART": "打开图表",
           "NEWS-DATA-1": "样本内联网新闻",
           "APPLICATIONS-DATA-1": "演示通过图表数据工作流程",
           "OPEN-IN-NEW-WINDOW": "在新窗口中打开",
           "OPEN-VIEWER": "打开浏览器",
           "GO-TO-CONSOLE": "转到控制台",
           "WINDOW": "窗口",
           "THIS-WINDOW": "该窗口",
           "COMPARE": "比较",
           "MAIN-ZONE-MESSAGE": "点击工具栏上的小工具控制打开的小工具！",
           "LOADING": "载入中",
           "GADGETS-ON-PANEL": "此面板上的小工具",
           "GADGETS-ACTIONS": "小配件操作",
           "OPEN-IN": "打开",
           "CLOSE": "关",
           "MOVE-TO": "搬去",
           "GADGET-OPENED-HERE": "小工具目前在这里隆重开幕",
           "NEW-WINDOW": "新窗户",
           "AWESOME": "真棒",
           "HOW-ARE-YOU": "你好吗",
           "INCOMES": "收入",
           "INCOMESCHART": "收入表",
           "MAP": "地图",
           "DESKTOP-MODE": "切换到桌面模式",
           "MOBILE-MODE": "切换到移动模式",
           "PERFORMANCE": "高性能网格"
        },
        "es": {
           "ABOUT": "Acerca de",
           "CONSOLE": "Consola",
           "VIEW-INTRODUCTION": "Ver Introducción",
           "VIEWER": "Espectador",
           "APPLICATIONS": "aplicaciones",
           "APPLICATIONS-CHART": "Tabla de aplicaciones",
           "HELLO": "Hola",
           "GRID": "Cuadrícula",
           "DATAGRID": "Cuadrícula de datos",
           "CHART": "Gráfico",
           "NEWS": "Noticias",
           "CLOSE-TAB": "Cerrar pestaña",
           "CLOSE-ALL-TABS": "Cierra todas las pestañas",
           "MOVE-ALL-TABS-TO": "Mover todas las fichas a",
           "CLOSE-OTHER-TABS": "Cerrar las otras pestañas",
           "FLIP-LEFT-RIGHT": "Voltear Izquierda Derecha",
           "FLIP-TOP-BOTTOM": "Voltear Superior Inferior",
           "FLIP-ORIENTATION": "flip Orientación",
           "COLLAPSE-RIGHT": "Contraer derecho",
           "COLLAPSE-LEFT": "Contraer izquierda",
           "COLLAPSE-TOP": "Collapse",
           "COLLAPSE-BOTTOM": "colapso Bottom",
           "MOVE-TO-LOCATION": "Mover a la ubicación",
           "SWITCH-USER": "Cambiar de usuario",
           "PREFERENCES": "preferencias",
           "OPEN-GADGETS-MENU": "Gadgets Abrir menú",
           "OPEN-APPLICATIONS": "Las aplicaciones abiertas",
           "OPEN-APPLICATIONS-CHART": "Tabla de aplicaciones abiertas",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "Noticias abierto",
           "OPEN-CHART": "Carta abierta",
           "NEWS-DATA-1": "Noticias de la muestra Intranet",
           "APPLICATIONS-DATA-1": "Demuestra los datos de flujo de trabajo a través de las cartas",
           "OPEN-IN-NEW-WINDOW": "Abrir en Nueva ventana",
           "OPEN-VIEWER": "Visor abierto",
           "GO-TO-CONSOLE": "Ir a la consola",
           "WINDOW": "Ventana",
           "THIS-WINDOW": "esta ventana",
           "COMPARE": "Comparar",
           "MAIN-ZONE-MESSAGE": "Haga clic en los controles de gadget barra de herramientas para abrir aparatos!",
           "LOADING": "Cargando",
           "GADGETS-ON-PANEL": "Aparatos de este panel",
           "GADGETS-ACTIONS": "acciones Gadget",
           "OPEN-IN": "abrirá en",
           "CLOSE": "Cerca",
           "MOVE-TO": "Mover a",
           "GADGET-OPENED-HERE": "Gadget Actualmente abrió aquí",
           "NEW-WINDOW": "Nueva ventana",
           "AWESOME": "Increíble",
           "HOW-ARE-YOU": "Cómo estás",
           "INCOMES": "ingresos",
           "INCOMESCHART": "Tabla de ingresos",
           "MAP": "Mapa",
           "DESKTOP-MODE": "Cambiar a modo de escritorio",
           "MOBILE-MODE": "Cambiar a modo de móvil",
           "PERFORMANCE": "Rejilla de Alto Rendimiento"
        },
        "hi": {
           "ABOUT": "के बारे में",
           "CONSOLE": "कंसोल",
           "VIEW-INTRODUCTION": "देखें परिचय",
           "VIEWER": "दर्शक",
           "APPLICATIONS": "अनुप्रयोगों",
           "APPLICATIONS-CHART": "आवेदन चार्ट",
           "HELLO": "नमस्ते",
           "GRID": "ग्रिड",
           "DATAGRID": "डेटा ग्रिड",
           "CHART": "चार्ट",
           "NEWS": "समाचार",
           "CLOSE-TAB": "टैब बंद करें",
           "CLOSE-ALL-TABS": "सभी टैब को बंद करें",
           "MOVE-ALL-TABS-TO": "करने के लिए सभी टैब ले जाएँ",
           "CLOSE-OTHER-TABS": "अन्य टैब बंद करें",
           "FLIP-LEFT-RIGHT": "फ्लिप बायां दायां",
           "FLIP-TOP-BOTTOM": "ऊपर से नीचे फ्लिप",
           "FLIP-ORIENTATION": "फ्लिप अभिविन्यास",
           "COLLAPSE-RIGHT": "अधिकार को संकुचित करें",
           "COLLAPSE-LEFT": "संकुचित वाम",
           "COLLAPSE-TOP": "संकुचित करें शीर्ष",
           "COLLAPSE-BOTTOM": "संक्षिप्त करें नीचे",
           "MOVE-TO-LOCATION": "स्थान पर ले जाने",
           "SWITCH-USER": "उपयोगकर्ता बदलें",
           "PREFERENCES": "पसंद",
           "OPEN-GADGETS-MENU": "ओपन गैजेट्स मेनू",
           "OPEN-APPLICATIONS": "ओपन आवेदन",
           "OPEN-APPLICATIONS-CHART": "ओपन आवेदन चार्ट",
           "OPEN-GRID": "ओपन ग्रिड",
           "OPEN-NEWS": "समाचार ओपन",
           "OPEN-CHART": "ओपन चार्ट",
           "NEWS-DATA-1": "नमूना इंट्रानेट समाचार",
           "APPLICATIONS-DATA-1": "चार्ट के माध्यम से कार्यप्रवाह डेटा दर्शाता",
           "OPEN-IN-NEW-WINDOW": "नई विंडो में खोलें",
           "OPEN-VIEWER": "ओपन व्यूअर",
           "GO-TO-CONSOLE": "कंसोल पर जाएं",
           "WINDOW": "खिड़की",
           "THIS-WINDOW": "इस विंडो",
           "COMPARE": "तुलना",
           "MAIN-ZONE-MESSAGE": "गैजेट को खोलने के लिए उपकरण पट्टी गैजेट नियंत्रण पर क्लिक करें!",
           "LOADING": "लोड हो रहा है",
           "GADGETS-ON-PANEL": "इस पैनल पर गैजेट्स",
           "GADGETS-ACTIONS": "गैजेट क्रिया",
           "OPEN-IN": "में खुलेगा",
           "CLOSE": "बंद करे",
           "MOVE-TO": "करने के लिए कदम",
           "GADGET-OPENED-HERE": "गैजेट वर्तमान में यहां खोला",
           "NEW-WINDOW": "नयी खिड़की",
           "AWESOME": "बहुत बढ़िया",
           "HOW-ARE-YOU": "क्या हाल है",
           "INCOMES": "आय",
           "INCOMESCHART": "आय चार्ट",
           "MAP": "नक्शा",
           "DESKTOP-MODE": "डेस्कटॉप मोड में स्विच",
           "MOBILE-MODE": "मोबाइल मोड में स्विच करें",
           "PERFORMANCE": "उच्च निष्पादन ग्रिड"
        },
        "ar": {
           "ABOUT": "حول",
           "CONSOLE": "وحدة التحكم",
           "VIEW-INTRODUCTION": "مشاهدة مقدمة",
           "VIEWER": "مشاهد",
           "APPLICATIONS": "تطبيقات",
           "APPLICATIONS-CHART": "تطبيقات الرسم البياني",
           "HELLO": "مرحبا",
           "GRID": "شبكة",
           "DATAGRID": "شبكة بيانات",
           "CHART": "خريطة",
           "NEWS": "أخبار",
           "CLOSE-TAB": "إغلاق علامة التبويب",
           "CLOSE-ALL-TABS": "إغلاق كافة علامات التبويب",
           "MOVE-ALL-TABS-TO": "نقل كافة علامات التبويب ل",
           "CLOSE-OTHER-TABS": "إغلاق علامات التبويب الأخرى",
           "FLIP-LEFT-RIGHT": "الوجه إلى اليسار إلى اليمين",
           "FLIP-TOP-BOTTOM": "الوجه أعلى القاع",
           "FLIP-ORIENTATION": "التوجيه الآخر",
           "COLLAPSE-RIGHT": "طي اليمين",
           "COLLAPSE-LEFT": "طي اليسار",
           "COLLAPSE-TOP": "طي الأعلى",
           "COLLAPSE-BOTTOM": "انهيار القاع",
           "MOVE-TO-LOCATION": "الانتقال إلى الموقع",
           "SWITCH-USER": "تغير المستخدم",
           "PREFERENCES": "تفضيلات",
           "OPEN-GADGETS-MENU": "الأدوات فتح القائمة",
           "OPEN-APPLICATIONS": "تطبيقات مفتوحة",
           "OPEN-APPLICATIONS-CHART": "تطبيقات مفتوحة الرسم البياني",
           "OPEN-GRID": "فتح الشبكة",
           "OPEN-NEWS": "أخبار مفتوحة",
           "OPEN-CHART": "فتح الرسم البياني",
           "NEWS-DATA-1": "عينة إنترانت الأخبار",
           "APPLICATIONS-DATA-1": "يوضح بيانات العمل عن طريق الرسوم البيانية",
           "OPEN-IN-NEW-WINDOW": "افتح في نافذة جديدة",
           "OPEN-VIEWER": "فتح عارض",
           "GO-TO-CONSOLE": "الذهاب إلى وحدة التحكم",
           "WINDOW": "نافذة او شباك",
           "THIS-WINDOW": "هذه النافذة",
           "COMPARE": "قارن",
           "MAIN-ZONE-MESSAGE": "انقر على الضوابط شريط الأدوات أداة لفتح الأدوات!",
           "LOADING": "جار التحميل",
           "GADGETS-ON-PANEL": "الأدوات على هذا الفريق",
           "GADGETS-ACTIONS": "تطبيقات التطبيقات المصغرة",
           "OPEN-IN": "فتح في",
           "CLOSE": "قريب",
           "MOVE-TO": "الانتقال إلى",
           "GADGET-OPENED-HERE": "أداة المفتوحة حاليا هنا",
           "NEW-WINDOW": "نافذة جديدة",
           "AWESOME": "رائع",
           "HOW-ARE-YOU": "كيف حالك",
           "INCOMES": "الدخل",
           "INCOMESCHART": "دخل الرسم البياني",
           "MAP": "خريطة",
           "DESKTOP-MODE": "التبديل إلى وضع سطح المكتب",
           "MOBILE-MODE": "التبديل إلى وضع المحمول",
           "PERFORMANCE": "شبكة عالية الأداء"
        },
        "pt": {
           "ABOUT": "Sobre",
           "CONSOLE": "Console",
           "VIEW-INTRODUCTION": "Ver Introdução",
           "VIEWER": "espectador",
           "APPLICATIONS": "aplicações",
           "APPLICATIONS-CHART": "aplicações Gráfico",
           "HELLO": "Olá",
           "GRID": "Grade",
           "DATAGRID": "Grade de dados",
           "CHART": "Gráfico",
           "NEWS": "Notícia",
           "CLOSE-TAB": "Aba fechada",
           "CLOSE-ALL-TABS": "Feche todas as guias",
           "MOVE-ALL-TABS-TO": "Mover a todas as guias",
           "CLOSE-OTHER-TABS": "Fechar outras guias",
           "FLIP-LEFT-RIGHT": "Virar Esquerda Direita",
           "FLIP-TOP-BOTTOM": "Flip Top inferior",
           "FLIP-ORIENTATION": "Orientação aleta",
           "COLLAPSE-RIGHT": "Recolher direito",
           "COLLAPSE-LEFT": "Recolher Esquerda",
           "COLLAPSE-TOP": "Recolher Top",
           "COLLAPSE-BOTTOM": "Fechar inferior",
           "MOVE-TO-LOCATION": "Mover-se para Localização",
           "SWITCH-USER": "Mudar de utilizador",
           "PREFERENCES": "preferências",
           "OPEN-GADGETS-MENU": "Abertas Gadgets menu",
           "OPEN-APPLICATIONS": "Aplicações abertas",
           "OPEN-APPLICATIONS-CHART": "Aplicações Open Chart",
           "OPEN-GRID": "Grade aberta",
           "OPEN-NEWS": "Abrir Notícias",
           "OPEN-CHART": "Abrir Gráfico",
           "NEWS-DATA-1": "Amostra Intranet Notícias",
           "APPLICATIONS-DATA-1": "Demonstra dados de fluxo de trabalho por meio de gráficos",
           "OPEN-IN-NEW-WINDOW": "Abrir em uma nova janela",
           "OPEN-VIEWER": "Abra o Visualizador",
           "GO-TO-CONSOLE": "Ir para Console",
           "WINDOW": "Janela",
           "THIS-WINDOW": "esta janela",
           "COMPARE": "Comparar",
           "MAIN-ZONE-MESSAGE": "Clique nos controles do gadget barra de ferramentas para abrir dispositivos!",
           "LOADING": "Carregando",
           "GADGETS-ON-PANEL": "Dispositivos neste painel",
           "GADGETS-ACTIONS": "ações Gadget",
           "OPEN-IN": "Aberto em",
           "CLOSE": "Fechar",
           "MOVE-TO": "Mover para",
           "GADGET-OPENED-HERE": "Gadget atualmente aberto aqui",
           "NEW-WINDOW": "Nova janela",
           "AWESOME": "Impressionante",
           "HOW-ARE-YOU": "Como você está",
           "INCOMES": "rendimentos",
           "INCOMESCHART": "rendimentos Gráfico",
           "MAP": "Mapa",
           "DESKTOP-MODE": "Alternar para o modo de desktop",
           "MOBILE-MODE": "Alternar para o modo móvel",
           "PERFORMANCE": "Grade de Alto Desempenho"
        },
        "bn": {
           "ABOUT": "সম্পর্কিত",
           "CONSOLE": "কনসোল",
           "VIEW-INTRODUCTION": "দেখুন ভূমিকা",
           "VIEWER": "দর্শক",
           "APPLICATIONS": "অ্যাপ্লিকেশন",
           "APPLICATIONS-CHART": "অ্যাপ্লিকেশন চার্ট",
           "HELLO": "হ্যালো",
           "GRID": "গ্রিড",
           "DATAGRID": "ডেটা গ্রিড",
           "CHART": "তালিকা",
           "NEWS": "খবর",
           "CLOSE-TAB": "ট্যাব বন্ধ করুন",
           "CLOSE-ALL-TABS": "সব ট্যাব বন্ধ",
           "MOVE-ALL-TABS-TO": "সব ট্যাব সরান",
           "CLOSE-OTHER-TABS": "অন্যান্য ট্যাব বন্ধ করুন",
           "FLIP-LEFT-RIGHT": "ফ্লিপ বাম ডান",
           "FLIP-TOP-BOTTOM": "শীর্ষ বটম ফ্লিপ",
           "FLIP-ORIENTATION": "ফ্লিপ স্থিতিবিন্যাস",
           "COLLAPSE-RIGHT": "রাইট সঙ্কুচিত করুন",
           "COLLAPSE-LEFT": "সঙ্কুচিত বাম",
           "COLLAPSE-TOP": "সঙ্কুচিত শীর্ষ",
           "COLLAPSE-BOTTOM": "সঙ্কুচিত বটম",
           "MOVE-TO-LOCATION": "অবস্থান সরান",
           "SWITCH-USER": "ব্যবহারকারী বদল করুন",
           "PREFERENCES": "পছন্দসমূহ",
           "OPEN-GADGETS-MENU": "ওপেন গ্যাজেটগুলি মেনু",
           "OPEN-APPLICATIONS": "খোলা অ্যাপ্লিকেশানগুলি",
           "OPEN-APPLICATIONS-CHART": "খোলা অ্যাপ্লিকেশানগুলি চার্ট",
           "OPEN-GRID": "ওপেন গ্রিড",
           "OPEN-NEWS": "সংবাদ খুলুন",
           "OPEN-CHART": "ওপেন চার্ট",
           "NEWS-DATA-1": "নমুনা ইন্ট্রানেট সংবাদ",
           "APPLICATIONS-DATA-1": "চার্ট মাধ্যমে কর্মপ্রবাহ তথ্য প্রমান",
           "OPEN-IN-NEW-WINDOW": "নতুন উইন্ডোতে খুলুন",
           "OPEN-VIEWER": "ওপেন ভিউয়ার",
           "GO-TO-CONSOLE": "কনসোল যান",
           "WINDOW": "জানলা",
           "THIS-WINDOW": "এই উইন্ডোটি",
           "COMPARE": "তুলনা করা",
           "MAIN-ZONE-MESSAGE": "গ্যাজেটগুলি খুলতে টুলবার গ্যাজেট নিয়ন্ত্রণ ক্লিক করুন!",
           "LOADING": "বোঝাই",
           "GADGETS-ON-PANEL": "এই প্যানেলে গ্যাজেটগুলি",
           "GADGETS-ACTIONS": "গ্যাজেট পদক্ষেপ",
           "OPEN-IN": "খোলা",
           "CLOSE": "ঘনিষ্ঠ",
           "MOVE-TO": "চলো",
           "GADGET-OPENED-HERE": "গ্যাজেট বর্তমানে এখানে খোলা",
           "NEW-WINDOW": "নতুন জানালা",
           "AWESOME": "অসাধারণ",
           "HOW-ARE-YOU": "আপনি কেমন আছেন",
           "INCOMES": "আয়",
           "INCOMESCHART": "আয়ের চার্ট",
           "MAP": "মানচিত্র",
           "DESKTOP-MODE": "ডেস্কটপ মোডে স্যুইচ করুন",
           "MOBILE-MODE": "মোবাইল মোডে স্যুইচ করুন",
           "PERFORMANCE": "হাই পারফরমেন্স গ্রিড"
        },
        "ru": {
           "ABOUT": "Около",
           "CONSOLE": "Консоль",
           "VIEW-INTRODUCTION": "Просмотр Введение",
           "VIEWER": "зритель",
           "APPLICATIONS": "Приложения",
           "APPLICATIONS-CHART": "Приложения Диаграмма",
           "HELLO": "Здравствуйте",
           "GRID": "сетка",
           "DATAGRID": "Data Grid",
           "CHART": "Диаграмма",
           "NEWS": "Новости",
           "CLOSE-TAB": "Закрыть вкладку",
           "CLOSE-ALL-TABS": "Закрыть все вкладки",
           "MOVE-ALL-TABS-TO": "Переместить все вкладки в",
           "CLOSE-OTHER-TABS": "Закрыть другие вкладки",
           "FLIP-LEFT-RIGHT": "Флип Left Right",
           "FLIP-TOP-BOTTOM": "Flip Top Bottom",
           "FLIP-ORIENTATION": "Флип ориентация",
           "COLLAPSE-RIGHT": "Collapse право",
           "COLLAPSE-LEFT": "Collapse слева",
           "COLLAPSE-TOP": "Свернуть Вверх",
           "COLLAPSE-BOTTOM": "Collapse Bottom",
           "MOVE-TO-LOCATION": "Переместить Расположение",
           "SWITCH-USER": "Поменять пользователя",
           "PREFERENCES": "предпочтения",
           "OPEN-GADGETS-MENU": "Открытые гаджеты Меню",
           "OPEN-APPLICATIONS": "Open Applications",
           "OPEN-APPLICATIONS-CHART": "Open Applications Chart",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "Открыть Новости",
           "OPEN-CHART": "Open Chart",
           "NEWS-DATA-1": "Пример Intranet Новости",
           "APPLICATIONS-DATA-1": "Демонстрирует данные рабочего процесса посредством диаграмм",
           "OPEN-IN-NEW-WINDOW": "Открыть в новом окне",
           "OPEN-VIEWER": "Открыть просмотр",
           "GO-TO-CONSOLE": "Перейти к консоли",
           "WINDOW": "Окно",
           "THIS-WINDOW": "Это окно",
           "COMPARE": "сравнить",
           "MAIN-ZONE-MESSAGE": "Нажмите на панели инструментов управления гаджета, чтобы открыть гаджеты!",
           "LOADING": "загрузка",
           "GADGETS-ON-PANEL": "Гаджеты на этой панели",
           "GADGETS-ACTIONS": "Гаджет действия",
           "OPEN-IN": "Открыть в",
           "CLOSE": "Закрыть",
           "MOVE-TO": "Переместить",
           "GADGET-OPENED-HERE": "Гаджет в настоящее время открыт здесь",
           "NEW-WINDOW": "Новое окно",
           "AWESOME": "Потрясающие",
           "HOW-ARE-YOU": "Как дела",
           "INCOMES": "доходов",
           "INCOMESCHART": "Доходы диаграммы",
           "MAP": "карта",
           "DESKTOP-MODE": "Переключение в режим рабочего стола",
           "MOBILE-MODE": "Переключение в мобильном режиме",
           "PERFORMANCE": "Высокая производительность сетки"
        },
        "ja": {
           "ABOUT": "約",
           "CONSOLE": "コンソール",
           "VIEW-INTRODUCTION": "ビューはじめに",
           "VIEWER": "ビューア",
           "APPLICATIONS": "アプリケーション",
           "APPLICATIONS-CHART": "アプリケーションチャート",
           "HELLO": "こんにちは",
           "GRID": "グリッド",
           "DATAGRID": "データグリッド",
           "CHART": "チャート",
           "NEWS": "ニュース",
           "CLOSE-TAB": "タブを閉じる",
           "CLOSE-ALL-TABS": "すべてのタブを閉じます",
           "MOVE-ALL-TABS-TO": "にすべてのタブを移動します",
           "CLOSE-OTHER-TABS": "他のタブを閉じます",
           "FLIP-LEFT-RIGHT": "左右フリップ",
           "FLIP-TOP-BOTTOM": "トップ下フリップ",
           "FLIP-ORIENTATION": "フリップオリエンテーション",
           "COLLAPSE-RIGHT": "右折りたたみます",
           "COLLAPSE-LEFT": "左折りたたみます",
           "COLLAPSE-TOP": "トップ折りたたみます",
           "COLLAPSE-BOTTOM": "折りたたみボトム",
           "MOVE-TO-LOCATION": "場所に移動",
           "SWITCH-USER": "ユーザーの切り替え",
           "PREFERENCES": "環境設定",
           "OPEN-GADGETS-MENU": "オープンガジェットメニュー",
           "OPEN-APPLICATIONS": "開いているアプリケーション",
           "OPEN-APPLICATIONS-CHART": "開いているアプリケーションチャート",
           "OPEN-GRID": "オープン・グリッド",
           "OPEN-NEWS": "オープンニュース",
           "OPEN-CHART": "オープンチャート",
           "NEWS-DATA-1": "サンプルイントラネットニュース",
           "APPLICATIONS-DATA-1": "チャートを介したワークフローデータをデモ",
           "OPEN-IN-NEW-WINDOW": "新しいウィンドウで開きます",
           "OPEN-VIEWER": "オープンビューア",
           "GO-TO-CONSOLE": "コンソールに移動",
           "WINDOW": "窓",
           "THIS-WINDOW": "このウィンドウ",
           "COMPARE": "比較します",
           "MAIN-ZONE-MESSAGE": "ガジェットを開くには、ツールバーのガジェットのコントロールをクリックして！",
           "LOADING": "積載",
           "GADGETS-ON-PANEL": "このパネル上のガジェット",
           "GADGETS-ACTIONS": "ガジェットアクション",
           "OPEN-IN": "で開きます。",
           "CLOSE": "閉じる",
           "MOVE-TO": "へ引っ越す",
           "GADGET-OPENED-HERE": "ガジェットは現在、ここに開かれました",
           "NEW-WINDOW": "新しい窓",
           "AWESOME": "驚くばかり",
           "HOW-ARE-YOU": "お元気ですか",
           "INCOMES": "収入",
           "INCOMESCHART": "所得チャート",
           "MAP": "地図",
           "DESKTOP-MODE": "デスクトップモードに切り替え",
           "MOBILE-MODE": "モバイルモードに切り替え",
           "PERFORMANCE": "高性能グリッド"
        },
        "pa": {
           "ABOUT": "ਬਾਰੇ",
           "CONSOLE": "ਕੰਸੋਲ",
           "VIEW-INTRODUCTION": "ਦੇਖੋ ਪਛਾਣ",
           "VIEWER": "ਦਰਸ਼ਕ",
           "APPLICATIONS": "ਐਪਲੀਕੇਸ਼ਨ",
           "APPLICATIONS-CHART": "ਕਾਰਜ, ਚਾਰਟ",
           "HELLO": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
           "GRID": "ਗਰਿੱਡ",
           "DATAGRID": "ਡਾਟਾ ਗਰਿੱਡ",
           "CHART": "ਚਾਰਟ",
           "NEWS": "ਨਿਊਜ਼",
           "CLOSE-TAB": "ਟੈਬ ਬੰਦ ਕਰੋ",
           "CLOSE-ALL-TABS": "ਸਾਰੇ ਟੈਬਸ ਬੰਦ ਕਰੋ",
           "MOVE-ALL-TABS-TO": "ਕਰਨ ਲਈ ਸਾਰੇ ਟੈਬਸ ਵਿੱਚ ਭੇਜੋ",
           "CLOSE-OTHER-TABS": "ਹੋਰ ਟੈਬਸ ਬੰਦ ਕਰੋ",
           "FLIP-LEFT-RIGHT": "ਝਟਕੋ ਖੱਬੇ ਸੱਜੇ",
           "FLIP-TOP-BOTTOM": "ਸਿਖਰ ਤਲ ਝਟਕੋ",
           "FLIP-ORIENTATION": "ਫਲਿਪ ਸਥਿਤੀ",
           "COLLAPSE-RIGHT": "ਸੱਜੇ ਸਮੇਟੋ",
           "COLLAPSE-LEFT": "ਸਮੇਟੋ ਖੱਬੇ",
           "COLLAPSE-TOP": "ਸਮੇਟੋ ਸਿਖਰ",
           "COLLAPSE-BOTTOM": "ਸੰਕੁਚਿਤ ਕਰੋ ਤਲ",
           "MOVE-TO-LOCATION": "ਲੋਕੈਸ਼ਨ ਭੇਜੋ",
           "SWITCH-USER": "ਸਵਿੱਚ ਯੂਜ਼ਰ",
           "PREFERENCES": "ਪਸੰਦ",
           "OPEN-GADGETS-MENU": "ਓਪਨ ਯੰਤਰ ਮੇਨੂ",
           "OPEN-APPLICATIONS": "ਓਪਨ ਐਪਲੀਕੇਸ਼ਨ",
           "OPEN-APPLICATIONS-CHART": "ਓਪਨ ਐਪਲੀਕੇਸ਼ਨ ਚਾਰਟ",
           "OPEN-GRID": "ਓਪਨ ਗਰਿੱਡ",
           "OPEN-NEWS": "ਨਿਊਜ਼ ਓਪਨ",
           "OPEN-CHART": "ਓਪਨ ਚਾਰਟ",
           "NEWS-DATA-1": "ਨਮੂਨਾ ਇੰਟਰਾਨੈੱਟ ਨਿਊਜ਼",
           "APPLICATIONS-DATA-1": "ਚਾਰਟ ਦੁਆਰਾ ਵਰਕਫਲੋ ਡਾਟਾ ਜ਼ਾਹਰ",
           "OPEN-IN-NEW-WINDOW": "ਨਵ ਵਿੰਡੋ ਵਿੱਚ ਖੋਲ੍ਹੋ",
           "OPEN-VIEWER": "ਓਪਨ ਦਰਸ਼ਕ",
           "GO-TO-CONSOLE": "ਕੰਸੋਲ ਤੇ ਜਾਓ",
           "WINDOW": "ਝਰੋਖਾ",
           "THIS-WINDOW": "ਇਹ ਵਿੰਡੋ",
           "COMPARE": "ਤੁਲਨਾ",
           "MAIN-ZONE-MESSAGE": "ਯੰਤਰ ਨੂੰ ਖੋਲ੍ਹਣ ਲਈ, ਟੂਲਬਾਰ 'ਗੈਜ਼ਟ ਕੰਟਰੋਲ' ਤੇ ਕਲਿੱਕ ਕਰੋ!",
           "LOADING": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ",
           "GADGETS-ON-PANEL": "ਇਸ ਪੈਨਲ 'ਤੇ ਯੰਤਰ",
           "GADGETS-ACTIONS": "ਗੈਜੇਟ ਕਾਰਵਾਈ",
           "OPEN-IN": "ਵਿਚ ਖੋਲ੍ਹੋ",
           "CLOSE": "ਬੰਦ ਕਰੋ",
           "MOVE-TO": "ਭੇਜੋ",
           "GADGET-OPENED-HERE": "ਗੈਜੇਟ ਵੇਲੇ ਇੱਥੇ ਖੋਲ੍ਹਿਆ",
           "NEW-WINDOW": "ਨਿਊ ਵਿੰਡੋ",
           "AWESOME": "ਬੇਨਜ਼ੀਰ",
           "HOW-ARE-YOU": "ਤੁਸੀ ਕਿਵੇਂ ਹੋ",
           "INCOMES": "ਆਮਦਨ",
           "INCOMESCHART": "ਆਮਦਨ ਚਾਰਟ",
           "MAP": "ਨਕਸ਼ਾ",
           "DESKTOP-MODE": "ਡੈਸਕਟਾਪ ਮੋਡ ਤੇ ਸਵਿਚ",
           "MOBILE-MODE": "ਮੋਬਾਈਲ 'ਮੋਡ ਤੇ ਸਵਿਚ",
           "PERFORMANCE": "ਹਾਈ ਕਾਰਗੁਜ਼ਾਰੀ ਗਰਿੱਡ"
        },
        "jv": {
           "ABOUT": "About",
           "CONSOLE": "console",
           "VIEW-INTRODUCTION": "View Pambuka",
           "VIEWER": "Viewer",
           "APPLICATIONS": "aplikasi",
           "APPLICATIONS-CHART": "aplikasi Chart",
           "HELLO": "Hello",
           "GRID": "kothak",
           "DATAGRID": "data Grid",
           "CHART": "Chart",
           "NEWS": "News",
           "CLOSE-TAB": "close Tab",
           "CLOSE-ALL-TABS": "Nutup kabeh tab",
           "MOVE-ALL-TABS-TO": "Pindhah kabeh tab kanggo",
           "CLOSE-OTHER-TABS": "Close tab liyane",
           "FLIP-LEFT-RIGHT": "Flip Kiri Kanan",
           "FLIP-TOP-BOTTOM": "Flip Top Bottom",
           "FLIP-ORIENTATION": "flip Orièntasi",
           "COLLAPSE-RIGHT": "ambruk Kanan",
           "COLLAPSE-LEFT": "ambruk Kiri",
           "COLLAPSE-TOP": "ambruk Top",
           "COLLAPSE-BOTTOM": "Collapse Bottom",
           "MOVE-TO-LOCATION": "Pindhah menyang Lokasi",
           "SWITCH-USER": "ngalih Anggota",
           "PREFERENCES": "Gawe",
           "OPEN-GADGETS-MENU": "Open Gadgets Menu",
           "OPEN-APPLICATIONS": "Open Aplikasi",
           "OPEN-APPLICATIONS-CHART": "Open Aplikasi Chart",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "Open News",
           "OPEN-CHART": "Open Chart",
           "NEWS-DATA-1": "Sample Intranet News",
           "APPLICATIONS-DATA-1": "Nduduhake data etos liwat denah",
           "OPEN-IN-NEW-WINDOW": "Bukak ing jendhela anyar",
           "OPEN-VIEWER": "Open Viewer",
           "GO-TO-CONSOLE": "Menyang Console",
           "WINDOW": "Window",
           "THIS-WINDOW": "jendhela iki",
           "COMPARE": "mbandhingaké",
           "MAIN-ZONE-MESSAGE": "Klik ing kontrol toolbar gadget kanggo mbukak Gadgets!",
           "LOADING": "Loading",
           "GADGETS-ON-PANEL": "Gadgets ing panel iki",
           "GADGETS-ACTIONS": "Tumindak gadget",
           "OPEN-IN": "Bukak ing",
           "CLOSE": "close",
           "MOVE-TO": "Pindhah menyang",
           "GADGET-OPENED-HERE": "Gadget saiki dibukak kene",
           "NEW-WINDOW": "jendela anyar",
           "AWESOME": "Apik",
           "HOW-ARE-YOU": "Piye kabare",
           "INCOMES": "asil",
           "INCOMESCHART": "asil Chart",
           "MAP": "Map",
           "DESKTOP-MODE": "Ngalih menyang mode desktop",
           "MOBILE-MODE": "Ngalih menyang mode mobile",
           "PERFORMANCE": "Performance dhuwur kothak"
        },
        "de": {
           "ABOUT": "Über",
           "CONSOLE": "Konsole",
           "VIEW-INTRODUCTION": "Ansicht Einführung",
           "VIEWER": "Zuschauer",
           "APPLICATIONS": "Anwendungen",
           "APPLICATIONS-CHART": "Anwendungstabelle",
           "HELLO": "Hallo",
           "GRID": "Gitter",
           "DATAGRID": "Data Grid",
           "CHART": "Diagramm",
           "NEWS": "Nachrichten",
           "CLOSE-TAB": "Tab schließen",
           "CLOSE-ALL-TABS": "Alle Fenster schließen",
           "MOVE-ALL-TABS-TO": "Verschieben Sie alle Registerkarten",
           "CLOSE-OTHER-TABS": "Andere Tabs schließen",
           "FLIP-LEFT-RIGHT": "Flip Left Right",
           "FLIP-TOP-BOTTOM": "Flip Top Bottom",
           "FLIP-ORIENTATION": "Flip Orientation",
           "COLLAPSE-RIGHT": "Collapse Rechts",
           "COLLAPSE-LEFT": "Collapse Left",
           "COLLAPSE-TOP": "Collapse Top",
           "COLLAPSE-BOTTOM": "Collapse Bottom",
           "MOVE-TO-LOCATION": "Umzug nach Ort",
           "SWITCH-USER": "Benutzer wechseln",
           "PREFERENCES": "Voreinstellungen",
           "OPEN-GADGETS-MENU": "Öffnen Sie Geräte-Menü",
           "OPEN-APPLICATIONS": "Open Applications",
           "OPEN-APPLICATIONS-CHART": "Open Applications Übersicht",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "Öffnen Sie Nachrichten",
           "OPEN-CHART": "Plan öffnen",
           "NEWS-DATA-1": "Beispiel Intranet News",
           "APPLICATIONS-DATA-1": "Demonstriert Workflow-Daten über Charts",
           "OPEN-IN-NEW-WINDOW": "In einem neuen Fenster öffnen",
           "OPEN-VIEWER": "Öffnen-Viewer",
           "GO-TO-CONSOLE": "Zum Console",
           "WINDOW": "Fenster",
           "THIS-WINDOW": "Dieses Fenster",
           "COMPARE": "Vergleichen",
           "MAIN-ZONE-MESSAGE": "Klicken Sie auf der Symbolleiste auf die Gadget-Steuerelemente Gadgets zu öffnen!",
           "LOADING": "Wird geladen",
           "GADGETS-ON-PANEL": "Gadgets auf diesem Panel",
           "GADGETS-ACTIONS": "Gadget Aktionen",
           "OPEN-IN": "öffnen Sie in",
           "CLOSE": "Schließen",
           "MOVE-TO": "Ziehen nach",
           "GADGET-OPENED-HERE": "Gadget sich hier eröffnet",
           "NEW-WINDOW": "Neues Fenster",
           "AWESOME": "Genial",
           "HOW-ARE-YOU": "Wie geht es Ihnen",
           "INCOMES": "Einkommen",
           "INCOMESCHART": "Einkommen-Diagramm",
           "MAP": "Karte",
           "DESKTOP-MODE": "Wechseln Sie in den Desktop-Modus",
           "MOBILE-MODE": "Wechseln Sie in den Mobilmodus",
           "PERFORMANCE": "High Performance Grid"
        },
        "ko": {
           "ABOUT": "약",
           "CONSOLE": "콘솔",
           "VIEW-INTRODUCTION": "보기 소개",
           "VIEWER": "뷰어",
           "APPLICATIONS": "응용 프로그램",
           "APPLICATIONS-CHART": "응용 프로그램 차트",
           "HELLO": "여보세요",
           "GRID": "그리드",
           "DATAGRID": "데이터 그리드",
           "CHART": "차트",
           "NEWS": "뉴스",
           "CLOSE-TAB": "탭 닫기",
           "CLOSE-ALL-TABS": "모든 탭을 닫습니다",
           "MOVE-ALL-TABS-TO": "모든 탭을 이동",
           "CLOSE-OTHER-TABS": "다른 탭 닫기",
           "FLIP-LEFT-RIGHT": "왼쪽 오른쪽 플립",
           "FLIP-TOP-BOTTOM": "위쪽에서 아래쪽 플립",
           "FLIP-ORIENTATION": "플립 방향",
           "COLLAPSE-RIGHT": "오른쪽 축소",
           "COLLAPSE-LEFT": "왼쪽 축소",
           "COLLAPSE-TOP": "최고 축소",
           "COLLAPSE-BOTTOM": "축소 바닥",
           "MOVE-TO-LOCATION": "위치로 이동",
           "SWITCH-USER": "사용자 전환",
           "PREFERENCES": "환경 설정",
           "OPEN-GADGETS-MENU": "열기 가젯 메뉴",
           "OPEN-APPLICATIONS": "응용 프로그램을 엽니 다",
           "OPEN-APPLICATIONS-CHART": "오픈 응용 프로그램 차트",
           "OPEN-GRID": "열기 격자",
           "OPEN-NEWS": "열기 뉴스",
           "OPEN-CHART": "열기 차트",
           "NEWS-DATA-1": "샘플 인트라넷 뉴스",
           "APPLICATIONS-DATA-1": "차트를 통해 워크 플로우 데이터를 보여줍니다",
           "OPEN-IN-NEW-WINDOW": "새 창에서 열기",
           "OPEN-VIEWER": "열기 뷰어",
           "GO-TO-CONSOLE": "콘솔로 이동",
           "WINDOW": "창문",
           "THIS-WINDOW": "이 창",
           "COMPARE": "비교",
           "MAIN-ZONE-MESSAGE": "가젯을 열려면 도구 모음 가젯 컨트롤을 클릭!",
           "LOADING": "로드",
           "GADGETS-ON-PANEL": "이 패널의 가젯",
           "GADGETS-ACTIONS": "가젯 조치",
           "OPEN-IN": "에서 열기",
           "CLOSE": "닫기",
           "MOVE-TO": "로 이동",
           "GADGET-OPENED-HERE": "가젯은 현재 여기에 오픈",
           "NEW-WINDOW": "새창",
           "AWESOME": "최고",
           "HOW-ARE-YOU": "어떻게 지냈어 요",
           "INCOMES": "소득",
           "INCOMESCHART": "소득 차트",
           "MAP": "지도",
           "DESKTOP-MODE": "바탕 화면 모드로 전환",
           "MOBILE-MODE": "모바일 모드로 전환",
           "PERFORMANCE": "고성능 그리드"
        },
        "fr": {
           "ABOUT": "Sur",
           "CONSOLE": "Console",
           "VIEW-INTRODUCTION": "Voir introduction",
           "VIEWER": "Téléspectateur",
           "APPLICATIONS": "Applications",
           "APPLICATIONS-CHART": "applications Graphique",
           "HELLO": "Bonjour",
           "GRID": "la grille",
           "DATAGRID": "Grille de données",
           "CHART": "Graphique",
           "NEWS": "Nouvelles",
           "CLOSE-TAB": "Fermer l'onglet",
           "CLOSE-ALL-TABS": "Fermer tous les onglets",
           "MOVE-ALL-TABS-TO": "Déplacer tous les onglets à",
           "CLOSE-OTHER-TABS": "Fermer les autres onglets",
           "FLIP-LEFT-RIGHT": "Retourner Gauche Droite",
           "FLIP-TOP-BOTTOM": "Flip Top Bottom",
           "FLIP-ORIENTATION": "Orientation flip",
           "COLLAPSE-RIGHT": "Réduire droit",
           "COLLAPSE-LEFT": "Réduire gauche",
           "COLLAPSE-TOP": "Réduire Haut",
           "COLLAPSE-BOTTOM": "GEOGRAPHIQUE",
           "MOVE-TO-LOCATION": "Déplacer vers l'emplacement",
           "SWITCH-USER": "Changer d'utilisateur",
           "PREFERENCES": "préférences",
           "OPEN-GADGETS-MENU": "Gadgets ouvrir le menu",
           "OPEN-APPLICATIONS": "Applications ouvertes",
           "OPEN-APPLICATIONS-CHART": "Graphique Open Applications",
           "OPEN-GRID": "Grille ouverte",
           "OPEN-NEWS": "Ouvrez Nouvelles",
           "OPEN-CHART": "Ouvrir graphique",
           "NEWS-DATA-1": "Nouvelles échantillon Intranet",
           "APPLICATIONS-DATA-1": "Démontre des données de flux de travail via des graphiques",
           "OPEN-IN-NEW-WINDOW": "Ouvrir dans une nouvelle fenetre",
           "OPEN-VIEWER": "Viewer open",
           "GO-TO-CONSOLE": "Aller à la console",
           "WINDOW": "Fenêtre",
           "THIS-WINDOW": "cette fenêtre",
           "COMPARE": "Comparer",
           "MAIN-ZONE-MESSAGE": "Cliquez sur les contrôles gadget barre d'outils pour ouvrir les gadgets!",
           "LOADING": "Chargement",
           "GADGETS-ON-PANEL": "Gadgets sur ce panneau",
           "GADGETS-ACTIONS": "Actions Gadget",
           "OPEN-IN": "Ouvrir dans",
           "CLOSE": "Fermer",
           "MOVE-TO": "Déménager à",
           "GADGET-OPENED-HERE": "Gadget actuellement ouvert ici",
           "NEW-WINDOW": "Nouvelle fenetre",
           "AWESOME": "Impressionnant",
           "HOW-ARE-YOU": "Comment allez-vous",
           "INCOMES": "Les revenus",
           "INCOMESCHART": "tableau des revenus",
           "MAP": "Carte",
           "DESKTOP-MODE": "Passer en mode bureau",
           "MOBILE-MODE": "Passer en mode mobile",
           "PERFORMANCE": "Grille haute performance"
        },
        "te": {
           "ABOUT": "గురించి",
           "CONSOLE": "కన్సోల్",
           "VIEW-INTRODUCTION": "పరిచయం వీక్షించండి",
           "VIEWER": "వ్యూయర్",
           "APPLICATIONS": "అప్లికేషన్స్",
           "APPLICATIONS-CHART": "అప్లికేషన్స్ చార్ట్",
           "HELLO": "హలో",
           "GRID": "గ్రిడ్",
           "DATAGRID": "డేటా గ్రిడ్",
           "CHART": "చార్ట్",
           "NEWS": "న్యూస్",
           "CLOSE-TAB": "టాబ్ మూసివేయి",
           "CLOSE-ALL-TABS": "అన్ని టాబ్లను మూసివేయి",
           "MOVE-ALL-TABS-TO": "అన్ని టాబ్లను తరలించు",
           "CLOSE-OTHER-TABS": "ఇతర టాబ్లను మూసివేయి",
           "FLIP-LEFT-RIGHT": "ఎడమ కుడి ఫ్లిప్",
           "FLIP-TOP-BOTTOM": "టాప్ దిగువ ఫ్లిప్",
           "FLIP-ORIENTATION": "ఫ్లిప్ దిశ",
           "COLLAPSE-RIGHT": "కుడి కుదించు",
           "COLLAPSE-LEFT": "ఎడమ కుదించు",
           "COLLAPSE-TOP": "కుదించు టాప్",
           "COLLAPSE-BOTTOM": "దిగువ కుదించు",
           "MOVE-TO-LOCATION": "స్థానానికి తరలించండి",
           "SWITCH-USER": "వినియోగదారుని మార్చు",
           "PREFERENCES": "ప్రాధాన్యతలు",
           "OPEN-GADGETS-MENU": "ఓపెన్ గాడ్జెట్లు మెనూ",
           "OPEN-APPLICATIONS": "ఓపెన్ అప్లికేషన్స్",
           "OPEN-APPLICATIONS-CHART": "ఓపెన్ అప్లికేషన్స్ చార్ట్",
           "OPEN-GRID": "ఓపెన్ గ్రిడ్",
           "OPEN-NEWS": "ఓపెన్ న్యూస్",
           "OPEN-CHART": "ఓపెన్ చార్ట్",
           "NEWS-DATA-1": "నమూనా ఇంట్రానెట్ న్యూస్",
           "APPLICATIONS-DATA-1": "పటాలు ద్వారా వర్క్ఫ్లో డేటా ప్రదర్శించాడు",
           "OPEN-IN-NEW-WINDOW": "క్రొత్త విండోలో తెరువు",
           "OPEN-VIEWER": "ఓపెన్ వ్యూయర్",
           "GO-TO-CONSOLE": "కన్సోల్ వెళ్ళండి",
           "WINDOW": "కిటికీ",
           "THIS-WINDOW": "ఈ విండో",
           "COMPARE": "సరిపోల్చండి",
           "MAIN-ZONE-MESSAGE": "గాడ్జెట్లు తెరవడానికి టూల్బార్ గాడ్జెట్ నియంత్రణల మీద క్లిక్ చేయండి!",
           "LOADING": "లోడ్",
           "GADGETS-ON-PANEL": "ఈ ప్యానెల్ లో గాడ్జెట్లు",
           "GADGETS-ACTIONS": "గాడ్జెట్ చర్యలు",
           "OPEN-IN": "లో తెరువు",
           "CLOSE": "Close",
           "MOVE-TO": "తరలించడానికి",
           "GADGET-OPENED-HERE": "గాడ్జెట్ ప్రస్తుతం ఇక్కడ ప్రారంభించారు",
           "NEW-WINDOW": "క్రొత్త విండో",
           "AWESOME": "బ్రహ్మాండం",
           "HOW-ARE-YOU": "మీరు ఎలా ఉన్నారు",
           "INCOMES": "ఆదాయాలతో",
           "INCOMESCHART": "ఆదాయాలతో చార్ట్",
           "MAP": "మ్యాప్",
           "DESKTOP-MODE": "డెస్క్టాప్ మోడ్కు మారండి",
           "MOBILE-MODE": "మొబైల్ మోడ్కు మారండి",
           "PERFORMANCE": "హై పెర్ఫార్మన్స్ గ్రిడ్"
        },
        "mr": {
           "ABOUT": "बद्दल",
           "CONSOLE": "कन्सोल",
           "VIEW-INTRODUCTION": "परिचय पहा",
           "VIEWER": "दर्शक",
           "APPLICATIONS": "अनुप्रयोग",
           "APPLICATIONS-CHART": "अनुप्रयोग चार्ट",
           "HELLO": "हॅलो",
           "GRID": "ग्रिड",
           "DATAGRID": "डेटा ग्रिड",
           "CHART": "चार्ट",
           "NEWS": "बातम्या",
           "CLOSE-TAB": "टॅब बंद करा",
           "CLOSE-ALL-TABS": "सर्व टॅब बंद करा",
           "MOVE-ALL-TABS-TO": "सर्व टॅब हलवा",
           "CLOSE-OTHER-TABS": "इतर टॅब बंद करा",
           "FLIP-LEFT-RIGHT": "डावा-उजवा फ्लिप",
           "FLIP-TOP-BOTTOM": "शीर्ष तळ फ्लिप",
           "FLIP-ORIENTATION": "फ्लिप ओरिएन्टेशन",
           "COLLAPSE-RIGHT": "उजव्या संकुचित",
           "COLLAPSE-LEFT": "डाव्या संकुचित",
           "COLLAPSE-TOP": "शीर्ष संकुचित",
           "COLLAPSE-BOTTOM": "तळ संकुचित",
           "MOVE-TO-LOCATION": "स्थान हलवा",
           "SWITCH-USER": "स्विच वापरकर्ता",
           "PREFERENCES": "प्राधान्ये",
           "OPEN-GADGETS-MENU": "ओपन गॅझेट मेनू",
           "OPEN-APPLICATIONS": "उघडा अनुप्रयोग",
           "OPEN-APPLICATIONS-CHART": "उघडा अनुप्रयोग चार्ट",
           "OPEN-GRID": "ग्रिड उघडा",
           "OPEN-NEWS": "बातम्या उघडा",
           "OPEN-CHART": "चार्ट उघडा",
           "NEWS-DATA-1": "नमुना इंट्रानेट बातम्या",
           "APPLICATIONS-DATA-1": "चार्ट द्वारे कार्यपद्धत डेटा प्रात्यक्षिक",
           "OPEN-IN-NEW-WINDOW": "नवीन विंडोमध्ये उघडा",
           "OPEN-VIEWER": "दर्शक उघडा",
           "GO-TO-CONSOLE": "कन्सोल वर जा",
           "WINDOW": "विंडो",
           "THIS-WINDOW": "ही विंडो",
           "COMPARE": "तुलना करा",
           "MAIN-ZONE-MESSAGE": "गॅझेट उघडण्यासाठी टूलबार गॅझेट नियंत्रणे वर क्लिक करा!",
           "LOADING": "लोड करीत आहे",
           "GADGETS-ON-PANEL": "या पटल गॅझेट",
           "GADGETS-ACTIONS": "गॅझेट क्रिया",
           "OPEN-IN": "उघडा",
           "CLOSE": "बंद",
           "MOVE-TO": "पुढे व्हा",
           "GADGET-OPENED-HERE": "गॅझेट सध्या येथे उघडले",
           "NEW-WINDOW": "नवीन विंडो",
           "AWESOME": "अप्रतिम",
           "HOW-ARE-YOU": "तू कसा आहेस",
           "INCOMES": "उत्पन्न",
           "INCOMESCHART": "उत्पन्न चार्ट",
           "MAP": "नकाशा",
           "DESKTOP-MODE": "डेस्कटॉप मोडवर स्विच करा",
           "MOBILE-MODE": "मोबाइल मोड कडे स्विच करा",
           "PERFORMANCE": "हाय परफॉर्मन्स ग्रिड"
        },
        "tr": {
           "ABOUT": "hakkında",
           "CONSOLE": "Konsol",
           "VIEW-INTRODUCTION": "Görünüm Tanıtım",
           "VIEWER": "izleyici",
           "APPLICATIONS": "Uygulamalar",
           "APPLICATIONS-CHART": "Uygulamalar Grafik",
           "HELLO": "Merhaba",
           "GRID": "Kafes",
           "DATAGRID": "Veri şebekesi",
           "CHART": "Grafik",
           "NEWS": "Haber",
           "CLOSE-TAB": "Sekmeyi Kapat",
           "CLOSE-ALL-TABS": "Tüm sekmeleri kapatma",
           "MOVE-ALL-TABS-TO": "Tüm sekmeleri taşı",
           "CLOSE-OTHER-TABS": "Diğer sekmeleri kapat",
           "FLIP-LEFT-RIGHT": "Sol Sağ çevirin",
           "FLIP-TOP-BOTTOM": "Üst Alt çevirin",
           "FLIP-ORIENTATION": "Ayaklı Yönlendirme",
           "COLLAPSE-RIGHT": "Sağa kapa",
           "COLLAPSE-LEFT": "Sol kapa",
           "COLLAPSE-TOP": "Üst kapa",
           "COLLAPSE-BOTTOM": "Collapse Alt",
           "MOVE-TO-LOCATION": "Yer taşı",
           "SWITCH-USER": "Kullanıcı değiştir",
           "PREFERENCES": "Tercihler",
           "OPEN-GADGETS-MENU": "Açık alet Menüsü",
           "OPEN-APPLICATIONS": "Açık Uygulamaları",
           "OPEN-APPLICATIONS-CHART": "Açık Uygulamalar Grafik",
           "OPEN-GRID": "Açık Izgara",
           "OPEN-NEWS": "Açık Haberler",
           "OPEN-CHART": "Açık Grafik",
           "NEWS-DATA-1": "Numune Intranet Haberleri",
           "APPLICATIONS-DATA-1": "çizelgeleri aracılığıyla iş akışı verilerini gösterir",
           "OPEN-IN-NEW-WINDOW": "Yeni pencerede aç",
           "OPEN-VIEWER": "Açık Görüntüleyici",
           "GO-TO-CONSOLE": "Konsolu'na gidin",
           "WINDOW": "pencere",
           "THIS-WINDOW": "Bu pencere",
           "COMPARE": "Karşılaştırmak",
           "MAIN-ZONE-MESSAGE": "gadget'larını açmak için araç çubuğu Gadget kontrolleri tıklayın!",
           "LOADING": "Yükleniyor",
           "GADGETS-ON-PANEL": "Bu panelde alet",
           "GADGETS-ACTIONS": "gadget İşlemleri",
           "OPEN-IN": "Açılmak",
           "CLOSE": "Kapat",
           "MOVE-TO": "Taşınmak",
           "GADGET-OPENED-HERE": "Gadget şu anda burada açıldı",
           "NEW-WINDOW": "Yeni Pencere",
           "AWESOME": "müthiş",
           "HOW-ARE-YOU": "Nasılsın",
           "INCOMES": "Gelirleri",
           "INCOMESCHART": "Gelirleri Grafik",
           "MAP": "Harita",
           "DESKTOP-MODE": "masaüstü moduna geç",
           "MOBILE-MODE": "Mobil moduna geç",
           "PERFORMANCE": "Yüksek Performanslı Izgara"
        },
        "ta": {
           "ABOUT": "பற்றி",
           "CONSOLE": "கன்சோல்",
           "VIEW-INTRODUCTION": "காண்க அறிமுகம்",
           "VIEWER": "பார்வையாளர்",
           "APPLICATIONS": "பயன்பாடுகள்",
           "APPLICATIONS-CHART": "பயன்பாடுகள் விளக்கப்படம்",
           "HELLO": "வணக்கம்",
           "GRID": "கிரிட்",
           "DATAGRID": "தரவு கிரிட்",
           "CHART": "விளக்கப்படம்",
           "NEWS": "செய்திகள்",
           "CLOSE-TAB": "தாவலை மூடுக",
           "CLOSE-ALL-TABS": "அனைத்து தாவல்களையும் மூடு",
           "MOVE-ALL-TABS-TO": "அனைத்து தாவல்கள் நகர்த்து",
           "CLOSE-OTHER-TABS": "மூடுக",
           "FLIP-LEFT-RIGHT": "இடது வலது மடக்கு",
           "FLIP-TOP-BOTTOM": "சிறந்த பாட்டம் மடக்கு",
           "FLIP-ORIENTATION": "திருப்பு திசை",
           "COLLAPSE-RIGHT": "வலது சுருக்கு",
           "COLLAPSE-LEFT": "இடது சுருக்கு",
           "COLLAPSE-TOP": "சிறந்த சுருக்கு",
           "COLLAPSE-BOTTOM": "சுருக்கு பாட்டம்",
           "MOVE-TO-LOCATION": "இருப்பிடம் நகர்த்து",
           "SWITCH-USER": "பயன்பாட்டாளர் மாற்றம்",
           "PREFERENCES": "விருப்பங்கள்",
           "OPEN-GADGETS-MENU": "திறந்த கேஜெட்கள் பட்டி",
           "OPEN-APPLICATIONS": "திறந்த பயன்பாடுகள்",
           "OPEN-APPLICATIONS-CHART": "திறந்த பயன்பாடுகள் விளக்கப்படம்",
           "OPEN-GRID": "திறந்த கட்டம்",
           "OPEN-NEWS": "திறந்த செய்திகள்",
           "OPEN-CHART": "திறந்த விளக்கப்படம்",
           "NEWS-DATA-1": "மாதிரி அக செய்திகள்",
           "APPLICATIONS-DATA-1": "வரைபடங்கள் வழியாக பணிப்போக்கு தரவு நிரூபிக்கிறது",
           "OPEN-IN-NEW-WINDOW": "புதிய சாளரத்தில் திற",
           "OPEN-VIEWER": "திறந்த பார்வையாளர்",
           "GO-TO-CONSOLE": "பணியகம் சென்று",
           "WINDOW": "ஜன்னல்",
           "THIS-WINDOW": "இந்த விண்டோ",
           "COMPARE": "ஒப்பிடு",
           "MAIN-ZONE-MESSAGE": "கேஜெட்டுகள் திறக்க டூல்பார் கேஜெட் கட்டுப்பாடுகள் கிளிக்!",
           "LOADING": "ஏற்றுதல்",
           "GADGETS-ON-PANEL": "இந்த குழு கேஜெட்கள்",
           "GADGETS-ACTIONS": "கேஜெட் செயல்கள்",
           "OPEN-IN": "திற",
           "CLOSE": "நெருக்கமான",
           "MOVE-TO": "நகர்த்து",
           "GADGET-OPENED-HERE": "கேஜெட் தற்போது இங்கு திறந்து",
           "NEW-WINDOW": "புதிய சாளரம்",
           "AWESOME": "அற்புதம்",
           "HOW-ARE-YOU": "எப்படி இருக்கிறீர்கள்",
           "INCOMES": "வருமானங்கள்",
           "INCOMESCHART": "வருமானங்கள் விளக்கப்படம்",
           "MAP": "வரைபடம்",
           "DESKTOP-MODE": "டெஸ்க்டாப் முறைக்கு மாறு",
           "MOBILE-MODE": "மொபைல் முறைக்கு மாறு",
           "PERFORMANCE": "உயர் செயல்திறன் கிரிட்"
        },
        "vi": {
           "ABOUT": "Trong khoảng",
           "CONSOLE": "Bảng điều khiển",
           "VIEW-INTRODUCTION": "Xem Giới thiệu",
           "VIEWER": "Người xem",
           "APPLICATIONS": "Các ứng dụng",
           "APPLICATIONS-CHART": "ứng dụng Chart",
           "HELLO": "xin chào",
           "GRID": "lưới",
           "DATAGRID": "Lưới dữ liệu",
           "CHART": "Đồ thị",
           "NEWS": "Tin tức",
           "CLOSE-TAB": "Đóng tab",
           "CLOSE-ALL-TABS": "Đóng tất cả cửa sổ",
           "MOVE-ALL-TABS-TO": "Di chuyển tất cả các tab để",
           "CLOSE-OTHER-TABS": "Đóng các tab khác",
           "FLIP-LEFT-RIGHT": "Lật Left Right",
           "FLIP-TOP-BOTTOM": "Lật Lên trên dưới",
           "FLIP-ORIENTATION": "Định hướng lật",
           "COLLAPSE-RIGHT": "Thu Ngay",
           "COLLAPSE-LEFT": "Thu Left",
           "COLLAPSE-TOP": "Thu Trang",
           "COLLAPSE-BOTTOM": "sụp đổ dưới",
           "MOVE-TO-LOCATION": "Di chuyển đến Location",
           "SWITCH-USER": "switch User",
           "PREFERENCES": "Sở thích",
           "OPEN-GADGETS-MENU": "Mở menu Tiện ích",
           "OPEN-APPLICATIONS": "ứng dụng mở",
           "OPEN-APPLICATIONS-CHART": "Mở ứng dụng Chart",
           "OPEN-GRID": "Open Grid",
           "OPEN-NEWS": "mở Tin tức",
           "OPEN-CHART": "mở Chart",
           "NEWS-DATA-1": "Mẫu Intranet Tin tức",
           "APPLICATIONS-DATA-1": "Thể hiện dữ liệu quy trình làm việc thông qua bảng xếp hạng",
           "OPEN-IN-NEW-WINDOW": "Open in new window",
           "OPEN-VIEWER": "mở Viewer",
           "GO-TO-CONSOLE": "Tới Bảng điều khiển",
           "WINDOW": "cửa sổ",
           "THIS-WINDOW": "cửa sổ này",
           "COMPARE": "So sánh",
           "MAIN-ZONE-MESSAGE": "Click vào thanh công cụ điều khiển tiện ích để mở tiện ích!",
           "LOADING": "Tải",
           "GADGETS-ON-PANEL": "Tiện ích trên bảng điều khiển này",
           "GADGETS-ACTIONS": "Hoạt động Gadget",
           "OPEN-IN": "Mở ra",
           "CLOSE": "Gần",
           "MOVE-TO": "Chuyển tới",
           "GADGET-OPENED-HERE": "Gadget hiện đang mở ở đây",
           "NEW-WINDOW": "Cửa sổ mới",
           "AWESOME": "Tuyệt vời",
           "HOW-ARE-YOU": "Bạn khỏe không",
           "INCOMES": "thu nhập",
           "INCOMESCHART": "thu nhập Chart",
           "MAP": "Bản đồ",
           "DESKTOP-MODE": "Chuyển sang chế độ máy tính để bàn",
           "MOBILE-MODE": "Chuyển sang chế độ điện thoại di động",
           "PERFORMANCE": "Hiệu suất cao Lưới"
        },
        "ur": {
           "ABOUT": "کے بارے میں",
           "CONSOLE": "کنسول",
           "VIEW-INTRODUCTION": "لنک کا تعارف",
           "VIEWER": "ناظرین",
           "APPLICATIONS": "درخواستیں",
           "APPLICATIONS-CHART": "درخواستیں چارٹ",
           "HELLO": "ہیلو",
           "GRID": "گرڈ",
           "DATAGRID": "ڈیٹا گرڈ",
           "CHART": "چارٹ",
           "NEWS": "خبریں",
           "CLOSE-TAB": "بند ٹیب",
           "CLOSE-ALL-TABS": "تمام ٹیبز بند کریں",
           "MOVE-ALL-TABS-TO": "کرنے کے لئے تمام ٹیبز میں منتقل کریں",
           "CLOSE-OTHER-TABS": "دیگر ٹیبز بند کریں",
           "FLIP-LEFT-RIGHT": "بائیں دائیں پلٹائیں",
           "FLIP-TOP-BOTTOM": "اوپر سے نیچے پلٹائیں",
           "FLIP-ORIENTATION": "پلٹائیں واقفیت",
           "COLLAPSE-RIGHT": "دایاں مختصر کریں",
           "COLLAPSE-LEFT": "بائیں بازو کی جماعتوں کو سکیڑیں",
           "COLLAPSE-TOP": "اوپر ختم کریں",
           "COLLAPSE-BOTTOM": "کھولیں بند کریں پایان",
           "MOVE-TO-LOCATION": "مقام پر منتقل",
           "SWITCH-USER": "استعمال کنندہ کو تبدیل کریں",
           "PREFERENCES": "ترجیحات",
           "OPEN-GADGETS-MENU": "اوپن کل پرزے مینو",
           "OPEN-APPLICATIONS": "کھولیں درخواستیں",
           "OPEN-APPLICATIONS-CHART": "کھولیں درخواستیں چارٹ",
           "OPEN-GRID": "اوپن گرڈ",
           "OPEN-NEWS": "کھولیں خبریں",
           "OPEN-CHART": "اوپن چارٹ",
           "NEWS-DATA-1": "نمونہ انٹرانیٹ خبریں",
           "APPLICATIONS-DATA-1": "چارٹ کے ذریعے کام کے فلو کو ڈیٹا کے ثبوت",
           "OPEN-IN-NEW-WINDOW": "نئی ونڈو میں کھولیں",
           "OPEN-VIEWER": "کھولیں ناظر",
           "GO-TO-CONSOLE": "کنسول پر جائیں",
           "WINDOW": "ونڈو",
           "THIS-WINDOW": "اس ونڈو",
           "COMPARE": "کا موازنہ کریں",
           "MAIN-ZONE-MESSAGE": "گیجٹ کو کھولنے کے لئے ٹول بار گیجٹ کنٹرول پر کلک کریں!",
           "LOADING": "لوڈ کر رہا ہے",
           "GADGETS-ON-PANEL": "اس پینل پر کل پرزے",
           "GADGETS-ACTIONS": "گیجٹ کے عوامل",
           "OPEN-IN": "میں کھولیں",
           "CLOSE": "بند کریں",
           "MOVE-TO": "پر منتقل",
           "GADGET-OPENED-HERE": "گیجٹ فی الحال یہاں کھول دیا",
           "NEW-WINDOW": "نئی کھڑکی",
           "AWESOME": "خوفناک",
           "HOW-ARE-YOU": "تم کیسی ہو",
           "INCOMES": "آمدنی",
           "INCOMESCHART": "آمدنی چارٹ",
           "MAP": "نقشہ",
           "DESKTOP-MODE": "ڈیسک ٹاپ طرز پر جائیں",
           "MOBILE-MODE": "موبائل طرز پر جائیں",
           "PERFORMANCE": "ہائی پرفارمنس گرڈ"
        }
     };
});